version: '3.8'

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
